### ISSUE TITLE
using az cli 2.34 but you are looking for cli 2.00

### ISSUE THREAD

**Issue by mickeyperlstein** [Azure/vscode-aks-tools#107] opened 2022-03-28 16:03 UTC
➜  ~ az version
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

---
# Error checking prerequisites
The Azure command line failed. See below for the error message. You may need to:

1. Log into the Azure CLI (run `az login` in the terminal)
1. Install the Azure CLI [(see the instructions for your operating system)](https://docs.microsoft.com/cli/azure/install-azure-cli)
1. Configure Kubernetes from the command line using the az acs or az aks command
Details

**Azure CLI 2.0 not found - install Azure CLI 2.0 and log in**

**Comment by itowlson** [comment] 2022-03-28 18:09
We don't look specifically for 2.0 - that message means the 2.0 stream because at the time there was also an Azure CLI 1.0 which was different, and we should probably update it to say "2" or "2.x" rather than "2.0".  2.34 ought to work but it looks like they've changed the output of `--version` again which breaks our checking.

That said, I think the bits of the extension that use the Azure CLI are mostly things we're planning on retiring.  Are you using this to register AKS clusters into kubectl using the Add Cluster wizard?  If so, a smoother way to do this is via the AKS extension (https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-aks-tools).  This adds your Azure clusters to the Cloud Explorer pane, from where you can add them to kubectl by right-clicking.  It also integrates better with other Azure extensions, doesn't depend on the CLI, and has a bunch of AKS diagnostic and other functionality.

I don't think the AKS extension handles Create Cluster fully autonomously yet though.  So if that's what you were doing we might need to get you a fix.

If neither of those is what you were doing when you hit this, could you let us know what you were doing, and we'll take a look.  Thanks!

**Comment by Tatsinnit** [comment] 2022-06-12 23:15
Thank you for the discussion, @mickeyperlstein if there something specific to reproduce this please share, or if this is still happening for you please let us know otherwise I will close this issue for now and you can re-open it with re-pro steps. Thanks. 🙏 ☕️

**Closed by Tatsinnit** 2022-06-12 23:15 UTC
